import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { products as produ } from "../../assets/dataProducts";
import Link from "next/link";
import { useRef } from "react";
import { montserrat } from "@/styles/fonts";
import { BsChevronLeft, BsChevronRight } from "react-icons/bs";
import styles from "../../styles/BrandsAll.module.css";

const BrandsDetail = () => {
  const router = useRouter();
  const { brand } = router.query;
  const scrollRef = useRef(null);

  const product = produ.filter((element) => element.brand === brand);

  const scrollButton = (scrollOffset) => {
    scrollRef.current.scrollLeft += scrollOffset;
  };

  return (
    <>
      <Head>
        <title>Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.productsAllContainer}>
        <div>
          <h1 className={`${montserrat.className} ${styles.title}`}>
            / {brand} /
          </h1>
        </div>
        <div className={styles.productsGlobalContainer}>
          <div className={styles.buttonContainer}>
            <button
              className={styles.productsContainer__btn}
              onClick={() => scrollButton(-300)}
            >
              <BsChevronLeft />
            </button>
          </div>

          <div className={styles.productsContainer} ref={scrollRef}>
            {product.map((item) => (
              <Link
                key={item.id}
                href={`/products/${item.id}`}
                className={styles.productsItem}
              >
                <Image
                  src={item.image}
                  alt="img"
                  width={200}
                  height={200}
                  className={styles.productImage}
                />
                <br />
                <br />
                <h2 key={item.id} className={montserrat.className}>
                  {item.name}
                </h2>
                <br />
                <p className={montserrat.className}>{item.tags}</p>
                <br />
                <button className={`${montserrat.className} ${styles.details}`}>
                  <h3>{`Details >`}</h3>
                </button>
              </Link>
            ))}
          </div>
          <div className={styles.buttonContainer}>
            <button
              className={styles.productsContainer__btn}
              onClick={() => scrollButton(300)}
            >
              <BsChevronRight />
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default BrandsDetail;
