import Head from "next/head";
import styles from "@/styles/BrandsAll.module.css";
import Image from "next/image";
import brand1 from "../../../public/assets/descargammmmm-removebg-preview.png";
import brand2 from "../../../public/assets/descarga-removebg-preview.png";
import brand3 from "../../../public/assets/descarga__1_-removebg-preview.png";
import Link from "next/link";
import { products as produ } from "../../assets/dataProducts";
import { useState } from "react";
import { montserrat } from "@/styles/fonts";

function BrandsAll() {
  const filterBrands = (brand) => {
    const lengthBrands = produ.filter((product) => {
      return product.brand === brand;
    });
    return lengthBrands.length;
  };
  const lengthWokpro = filterBrands("workpro");
  const lengthEquipson = filterBrands("equipson");
  const lengthLightshark = filterBrands("lightshark");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      <main className={styles.bransALlContainer}>
=======

      <main className={styles.bransAllContainer}>
>>>>>>> 12cc3edcb8f2b2be4ee161309e21af48c07085c8
        <section className={styles.bransALlContainer__title}>
          <h1 className={montserrat.className}>ASSOCIATED BRANDS</h1>
        </section>

        <section className={styles.bransAllContainer__brands}>
          <article className={styles.bransAllContainer__brand__conteiner}>
            <div className={prompt.className}>
              <Link href={`/brands/workpro`}>
                <Image src={brand1} alt="brand1" width={200} height={150} />
              </Link>
              <p className={styles.bransAllContainer__brands__paragraf}>WORKPRO {`(${lengthWokpro})`} </p>
            </div>
          </article>
<<<<<<< HEAD
          <article className={styles.bransAllContainer__brand__conteiner}>
            <div className={prompt.className}>
=======

          <article className={styles.bransAllContainer__brand2}>
            <div className={styles.bransAllContainer__brand__circle}>
>>>>>>> 12cc3edcb8f2b2be4ee161309e21af48c07085c8
              <Link href={`/brands/lightshark`}>
                <Image src={brand2} alt="brand2" width={200} height={150} />
              </Link>
              <p className={styles.bransAllContainer__brands__paragraf}>LIGTHSHRK {`(${lengthLightshark})`}</p>
            </div>
          </article>
<<<<<<< HEAD
          <article className={styles.bransAllContainer__brand__conteiner}>
            <div className={prompt.className}>
=======

          <article className={styles.bransAllContainer__brand3}>
            <div className={styles.bransAllContainer__brand__circle}>
>>>>>>> 12cc3edcb8f2b2be4ee161309e21af48c07085c8
              <Link href={`/brands/equipson`}>
                <Image src={brand3} alt="brand3" width={200} height={150} />
              </Link>
              <p className={styles.bransAllContainer__brands__paragraf}>EQUIPSON {`(${lengthEquipson})`}</p>
            </div>
          </article>
        </section>
      </main>
    </>
  );
}

export default BrandsAll;
