import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/ProductDetailPage.module.css";
import { useRouter } from "next/router";
import { products as produ } from "../../assets/dataProducts";
import { montserrat } from "@/styles/fonts";

const ProductDetailPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const product = produ.filter((element) => element.id.toString() === id);

  return (
    <>
      <Head>
        <title>Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoIcon1.ico" />
      </Head>

      <main className={montserrat.className}>
        {product.map((item) => (
          <>
            <section className={styles.ProductDetailContainer__mainConteiner}>
              <section className={styles.ProductDetailContainer__info}>
                <article>
                  <Image
                    src={item.image}
                    alt="productDetail"
                    width={500}
                    height={450}
                  />
                </article>

                <article className={styles.ProductDetailContainer__description}>
                  <div>
                    <h2>{item.name}</h2>
                    <p>{item.brand}</p>
                    <br />
                    <span
                      className={
                        styles.ProductDetailContainer__description__tag
                      }
                    >
                      {item.tags}
                    </span>
                    <br />
                    <br />
                    <p>{item.description}</p>
                    <br />
                    <p>{item.description2}</p>
                  </div>
                </article>
              </section>
            </section>
          </>
        ))}
      </main>
    </>
  );
};

export default ProductDetailPage;
